import { SubCategoryRepositoryAction, SubCategoryRepositoryCreateAction, SubCategoryRepositoryDeleteAction, SubCategoryRepositoryErrorAction, SubCategoryRepositoryGetAllAction, SubCategoryRepositoryGetByCategoryAction, SubCategoryRepositoryGetByIdAction, SubCategoryRepositoryUpdateAction } from "../actions";

export type ActionSubCategory=
|SubCategoryRepositoryAction
|SubCategoryRepositoryCreateAction
|SubCategoryRepositoryUpdateAction
|SubCategoryRepositoryDeleteAction
|SubCategoryRepositoryGetAllAction
|SubCategoryRepositoryGetByIdAction
|SubCategoryRepositoryErrorAction
|SubCategoryRepositoryGetByCategoryAction

